# Generated by Django 4.2.23 on 2026-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
