# Generated by Django 4.2.13 on 2024-08-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='personal_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.personaldata'),
        ),
    ]
