# Generated by Django 4.2.23 on 2026-06-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recover_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
