# Generated by Django 4.2.13 on 2025-08-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_personaldata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaldata', to='user.address'),
        ),
    ]
