# Generated by Django 4.2.13 on 2024-09-13 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='autor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='posts',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.organ'),
        ),
        migrations.AddField(
            model_name='posts',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.specie'),
        ),
        migrations.AddField(
            model_name='point',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.posts'),
        ),
    ]
