# Generated by Django 4.2.13 on 2024-08-28 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('veterinary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideMicroscopyPost',
            new_name='Posts',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='slide',
            new_name='posts',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='image_slide',
            new_name='image',
        ),
    ]
