# Generated by Django 4.2.13 on 2024-08-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_slidemicroscopypost_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='type_post',
            field=models.IntegerField(choices=[(1, 'Histologia'), (2, 'Patologia')], default=1),
        ),
    ]
