# Generated by Django 4.2.13 on 2024-10-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_point_analyzed_functions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
