# Generated by Django 4.2.13 on 2024-10-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_point_analyzed_functions_point_analyzed_structures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='color',
            field=models.CharField(choices=[('yellow', 'Amarelo'), ('blue', 'Azul'), ('red', 'Vermelho')], max_length=10),
        ),
    ]
