# Generated by Django 4.2.13 on 2025-08-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_point_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
