# Generated by Django 4.2.13 on 2024-09-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('field_name', models.URLField()),
                ('document_supporting_material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.document')),
                ('image_supporting_material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.system')),
            ],
        ),
    ]
