# Generated by Django 4.2.13 on 2024-11-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('supporting_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingmaterial',
            name='document_supporting_material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
