# Generated by Django 4.2.13 on 2025-08-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
        ('supporting_materials', '0003_alter_supportingmaterial_document_supporting_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingmaterial',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.system'),
        ),
    ]
