# Generated by Django 4.2.13 on 2024-06-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
