# Generated by Django 4.2.13 on 2024-07-02 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabrica_histologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_organ', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='image_system',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.CreateModel(
            name='SlideMicroscopyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analysis', models.DateField()),
                ('post_date', models.DateField()),
                ('species', models.CharField(max_length=255)),
                ('type_cut', models.CharField(max_length=255)),
                ('increase', models.CharField(max_length=255)),
                ('coloring', models.CharField(max_length=255)),
                ('autor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('image_slide', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_histologia.organ')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('position', models.JSONField()),
                ('color', models.CharField(max_length=255)),
                ('analyzed_structures', models.CharField(max_length=255)),
                ('analyzed_functions', models.CharField(max_length=255)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_histologia.slidemicroscopypost')),
            ],
        ),
        migrations.AddField(
            model_name='organ',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica_histologia.system'),
        ),
    ]
