# Generated by Django 4.2.23 on 2025-12-12 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veterinary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.IntegerField(choices=[(1, 'GERAL'), (2, 'SISTEMA')])),
                ('level', models.IntegerField(blank=True, choices=[(1, 'FACIL'), (2, 'MEDIO'), (3, 'DIFICIL')], null=True)),
                ('score', models.IntegerField(default=0)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_system', to='veterinary.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=155, null=True)),
                ('question', models.TextField()),
                ('level', models.IntegerField(blank=True, choices=[(1, 'FACIL'), (2, 'MEDIO'), (3, 'DIFICIL')], null=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.system')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('correct', models.BooleanField()),
                ('comment_answer', models.TextField(blank=True, default='', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
