# Generated by Django 4.2.23 on 2025-12-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
