# Generated by Django 4.2.13 on 2024-10-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.TextField(max_length=155, null=True),
        ),
    ]
