# Generated by Django 4.2.23 on 2025-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.TextField(blank=True, default='', max_length=155, null=True),
        ),
    ]
