# Generated by Django 4.2.13 on 2024-10-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(choices=[(1, 'FACIL'), (2, 'MEDIO'), (3, 'DIFICIL')]),
        ),
    ]
