# Generated by Django 4.2.13 on 2025-08-13 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0001_initial'),
        ('quiz', '0003_alter_quiz_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.IntegerField(choices=[(1, 'GERAL'), (2, 'SISTEMA')])),
                ('level', models.IntegerField(blank=True, choices=[(1, 'FACIL'), (2, 'MEDIO'), (3, 'DIFICIL')], null=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_system', to='veterinary.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
