# Generated by Django 4.2.13 on 2025-08-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
