# Generated by Django 4.2.13 on 2025-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_answer_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment_answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.TextField(),
        ),
    ]
